apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Apache on GKE</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .container { max-width: 800px; margin: 0 auto; }
            .header { background-color: #f4f4f4; padding: 20px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 Apache2 Running on GKE!</h1>
                <p>This Apache server is running in a Kubernetes container on Google Kubernetes Engine.</p>
                <p><strong>Server Time:</strong> <span id="time"></span></p>
                <p><strong>Container:</strong> Apache HTTP Server 2.4</p>
                <p><strong>Kubernetes:</strong> Google Kubernetes Engine</p>
            </div>
        </div>
        <script>
            function updateTime() {
                document.getElementById('time').textContent = new Date().toLocaleString();
            }
            updateTime();
            setInterval(updateTime, 1000);
        </script>
    </body>
    </html>